language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
  - './node_modules/karma/bin/karma start test/karma.conf.js'
  - './node_modules/protractor/bin/webdriver-manager update'
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &" - sleep 5
  - './node_modules/protractor/bin/protractor protractor-config.js'