language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: "PEIIuOqPVRUcQLhvS1Dma5hsfMf/5QqBt2/cuO6F7chHCRS5zASGi8/S2nbmfOElbPLGO4/Kgg4aKZYWDpGnmcrjjT0t4DDqpaVPAtXG7FhrICzRNrux2jmwT2rs0el03nETmtyOEm2DuVfD7yYKIoUUfj9YFPsMbpEWJEnrHJrVwTUTrdWvV09Hb9wxFLecu3reHam7XFFItTsQCYuUDQ/Mf1RH/eFpvI5xf0ccr3c10f4WGzsIG+1ZKUx38EeSSWh+SaWVFZq0dYSKPtnyjRWgDMQVhB2ihymsRg8Mis5x0ft9+dKi099sGBXUo7hHTSnXwvFM2FfAN+gjlZprnCzQS/K577cilPVCByTyJFNmecbcr3+fSFKppvzy85av2suXUiTh8wijc1/vBflmo0HupHNGPT0i3aecj2pNASMwbl8tEXiN6xUbJhDJDnPAgMN4Qv+TFhDxqArdEjkhJ9Ag/wgMeSSmarBnd9m2dR0im1sj4Bao0qnPH+5/D28o6Pc6OWOMY+NXujr76YGBzBsXq7BJ4zYrCrGsV/s5Qu36LYoMCEDBNhptWeMsXWWRw0PcwMz+Ji8sdU2b7NziZJXs/3lZRkUmIQZYRXz5lmQfUx3ththQV8QdJL63M4YNsrDPjbmhqhnU8mlW2+I9FElUQFYZzJmcRDV32wJ7Q7k="
    - secure: "QMc2/atV9UBjQYj1ZB3Tjpo/pijEWkgHHXM0OTzpKiWV3I/RX3abyR3ohTi35C38BbI50sn4ZmHFY+l3W/v09D6BnY2kK2FgUsGAcD1Cl1ZU4veqOPgcsoJ7c7KK74zCm77u8BA52G7wvOfiQIJ94Cmja5ry3904ic2S2F5sShndtxtgh4CleeSYrlnzllI2pLn2pARBqOFWZ3lMDvFuCWxNCNJoD/22hQN/eEUZr4oFC7HdHDKzIyzQEe37j2dcZPNKVUgvX5uBd++KdML6Z7umPvTidV+xmw+Rs6zx7jSQM5G+NMni0NhUXgt5P8l1a3PqZLrlxy2QzT2F2AdSAkjHBD7g+1VhWceTj4AeFhHDnCpzdWXPXjwbfci6iFiSNyHZpJ+b0l6C0S0H3aIYB1clh+auQZB6taHk48L+1pjnNvhUvnDvqwnAUZbTz4zFtD8h+a13N0jvfdsrqPvWLFoty1qcBV2402s1DdK6Q5sQwysMb8PROISBKNfNOlSKGyPnuinSH01ng/ZIt3UjECXEz0GHYXwMsFHGzLJ6V3kXMymI/41Bsg0qKDMSvQUJAKvSFZ4U4pTNs6EMResNfZipe6aSpaIdOok859SLHwfo+iNAU8sWMhRBgZGRYSL/yoSZfpMtXcyNWw0VdySKKU//Dd29xbmvgN2+Jnpi3n8="
addons:
  sauce_connect: true

before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'grunt travis'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"