language: python
python:
  - "3.4"

sudo: required
addons:
  postgresql: '9.3'
services: postgresql

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - 'cd ..'
  - 'git clone https://github.com/HackSoftware/Loki.git'
install:
  - 'sudo pip install -r Loki/requirements.txt'
  - 'nvm install 0.10'

before_script:
  - sleep 3 # give xvfb some time to start
  - psql -c 'CREATE DATABASE testdb;' -U postgres
  - 'python Loki/loki/manage.py migrate'
  - 'python Loki/loki/manage.py runserver &'
  
  - 'cd test-repo'
  - 'npm update -g npm'
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - 'grunt travis'