language: node_js
node_js:
  - '0.10'
python:
- '3.4'
sudo: required
addons:
  postgresql: '9.3'
services: postgresql

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - 'git clone https://github.com/HackSoftware/Loki.git'
install:
  - 'sudo pip install -r Loki/requirements.txt'


before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


script:
  - 'python loki/manage.py migrate'
  - 'grunt karma:unit'
  - 'grunt travis'